# This file provides rules for project code style.
# Read https: //prettier.io/docs/en/options.html for additional information.

bracketSpacing: true
jsxBracketSameLine: true
printWidth: 80
semi: true
singleQuote: true
tabWidth: 2
trailingComma: "es5"
